package com.alost.microstep.data.model.database.core;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PedometerDailyDetail".
 */
public class PedometerDailyDetailEntity {

    private Long id;
    private Integer stepCount;
    private Long startTime;
    private Long endTime;
    private Long delTime;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PedometerDailyDetailEntity() {
    }

    public PedometerDailyDetailEntity(Long id, Integer stepCount, Long startTime, Long endTime, Long delTime) {
        this.id = id;
        this.stepCount = stepCount;
        this.startTime = startTime;
        this.endTime = endTime;
        this.delTime = delTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStepCount() {
        return stepCount;
    }

    public void setStepCount(Integer stepCount) {
        this.stepCount = stepCount;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Long getDelTime() {
        return delTime;
    }

    public void setDelTime(Long delTime) {
        this.delTime = delTime;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
